### PR TITLE
Pulling Masters Into gh-pages

### PR DESCRIPTION
**Pull request by bradley-doyle**

### CODE REVIEW

**Comment by bradley-doyle** [comment]
@tiffanytse @chan0345 @elisak 
It's saying that there is a commit problem but not showing me what need to change if one of you can see whats happening that be awesome. 

Thanks

**Comment by tiffanytse** [comment]
Were you committing to master?

**Comment by bradley-doyle** [comment]
At some point someone did commit to masters. But More problems came up and we moved the repo over to https://github.com/gumbey/bluevoice

**Comment by elgh0019** [comment]
@tiffanytse 

So yes on the old repository which is under my github, there were commits on both gh-pages and masters, thats why we started a new repository under Brad's  account (we had a lot of problem with the fact that we originally committed to masters). I sent you both links just so that you see previous commits. 
The new working repo is here - https://github.com/gumbey/bluevoice
Thanks!

**Pull request closed without merging**
